In [8]:
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9]])

arr3 = np.append(arr1, arr2, axis =0)
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr4 = np.array([[1,2,3], [4,5,6]])
arr5 = np.insert(arr4, 1, 10, axis=0)
arr6 = np.insert(arr4, 1, 10, axis=1)
print(arr5, arr6)

[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]] [[ 1 10  2  3]
 [ 4 10  5  6]]


In [20]:
arr7 = np.array([[2,1,6],[0,7,4],[5,3,2]])

#sort는 기본이 오름차순을 기준으로 정렬
arr8 = np.sort(arr7, axis = 0)
print(arr8)

arr9 = np.sort(arr7, axis = 1)
print(arr9)

[[0 1 2]
 [2 3 4]
 [5 7 6]]
[[1 2 6]
 [0 4 7]
 [2 3 5]]


In [21]:
# 내림차순 정렬 객체[np.argsort(-객체)] , .sort()[::-1]
arr10 = np.array([4,2,6,5,1,3,0])
arr11 = arr10[np.argsort(-arr10)]
print(arr11)

[6 5 4 3 2 1 0]
